version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  api:
    build: back-end/api-task-manager
    ports:
      - "3000:3000"
    environment:
       DATABASE_URL: postgresql://root:root@db:5432/postgres?schema=public
    depends_on:
      - db

  app:
    build:
      context: front-end/web-task-manager
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - api

volumes:
  data:
